import 'package:flutter/material.dart';
import 'package:provider/provider.dart';
import 'package:shared_preferences/shared_preferences.dart';

class LanguageProvider with ChangeNotifier {
  Locale _locale = const Locale('en');
  bool _isLoading = true;

  Locale get locale => _locale;
  bool get isLoading => _isLoading;
  bool get isArabic => _locale.languageCode == 'ar';

  LanguageProvider() {
    _loadLanguage();
  }

  void toggleLanguage() {
    final newLanguage = _locale.languageCode == 'ar'
        ? 'en'
        : (_locale.languageCode == 'en' ? 'fr' : 'en');
    setLanguage(newLanguage);
  }

  static final Map<String, Map<String, String>> _translations = {
    'en': {
      'welcome': 'Welcome to Darna',
      'welcome_subtitle':
          'Discover the perfect property in Morocco.\nYour journey to a new home starts here.',
      'get_started': 'Get Started',
      'signin': 'Sign In',
      'signup': 'Sign Up',
      'email': 'Email',
      'password': 'Password',
      'forgot_password': 'Forgot Password?',
      'or': 'OR',
      'dont_have_account': "Don't have an account? ",
      'already_have_account': 'Already have an account? ',
      'full_name': 'Full Name',
      'phone': 'Phone Number',
      'create_account': 'Create your account to continue',
      'account_created': 'Account Created!',
      'welcome_darna': 'Welcome to the Darna family!',
      'profile': 'Profile',
      'edit_profile': 'Edit Profile',
      'settings': 'Settings',
      'language': 'Language',
      'dark_mode': 'Dark Mode',
      'light_mode': 'Light Mode',
      'logout': 'Logout',
      'coming_soon': 'Coming Soon!',
      'update': 'Update Profile',
      'success': 'Success',
      'profile_updated': 'Profile updated successfully!',
      'social_accounts': 'Social Accounts',
      'link': 'Link',
      'unlink': 'Unlink',
      'listings_count': 'Listings',
      'sold_count': 'Sold',
      'reviews_count': 'Reviews',
      'transactions_count': 'Transactions',
      'no_sold_properties': 'No Sold Properties',
      'no_sold_subtitle': 'Your sold properties will appear here',
      'hello': 'Hello 👋',
      'categories': 'Categories',
      'featured_properties': 'Featured Properties',
      'best_deals': 'Best deals for you',
      'top_locations': 'Top Locations',
      'explore_popular': 'Explore popular areas',
      'best_for_rent': 'Best For Rent',
      'monthly_rental': 'Monthly rental options',
      'search_properties': 'Search properties...',
      'see_all': 'See All',
      'explore': 'Explore',
      'properties': 'Properties',
      'agents': 'Agents',
      'listings_suffix': 'listings',
      // Navigation
      'nav_home': 'Home',
      'nav_search': 'Search',
      'nav_favorites': 'Favorites',
      'nav_profile': 'Profile',
      'nav_messages': 'Messages',
      // Chat
      'messages': 'Messages',
      'conversations': 'Conversations',
      'no_conversations': 'No conversations yet',
      'no_conversations_desc':
          'Start chatting by contacting a property owner from the property details page.',
      'no_messages': 'No messages yet. Say hello!',
      'type_message': 'Type a message...',
      'send': 'Send',
      'chat_auto_message': 'Salam, I am interested in this property.',
      'cannot_chat_own':
          'You cannot chat with yourself about your own property.',
      'typing': 'typing...',
      'online': 'Online',
      'last_seen': 'last seen',
      'delete_for_me': 'Delete for me',
      'delete_for_everyone': 'Delete for everyone',
      'message_deleted': 'This message was deleted',
      'recording': 'Recording...',

      // Reviews & Ratings
      'leave_review': 'Leave a Review',
      'edit_review': 'Edit Review',
      'delete_review': 'Delete Review',
      'submit_review': 'Submit Review',
      'review_success': 'Review submitted successfully',
      'review_updated_success': 'Review updated successfully',
      'review_deleted_success': 'Review deleted successfully',
      'owner_review_error': 'You cannot review your own property.',
      'duplicate_review_error': 'You have already reviewed this property.',
      'rating_required': 'Rating is required (1-5 stars).',

      // Property Details
      'bedrooms': 'Bedrooms',
      'bathroom': 'Bathroom',
      'location_facilities': 'Location & Public Facilities',
      'cost_of_living': 'Cost of Living',
      'see_details': 'See details',
      'reviews': 'Reviews',
      'view_all_reviews': 'View all reviews',
      'view_property': 'View Property',
      'view_on_map': 'View on Map',
      'nearby_properties': 'Nearby Properties',
      'nearby_location': 'Nearby From this Location',
      'mad': 'MAD',
      'month': 'month',
      'drive': 'drive',
      'map_view': 'Map View Placeholder',
      'contact_agent': 'Contact Agent (Coming Soon)',
      'ar_view': 'AR View (Coming Soon)',
      'my_favorites': 'My Favorites',
      'favorites': 'Favorites',
      'favorite': 'Favorite',
      'clear_all': 'Clear All',
      'empty_favorites_title': 'Your favorite page is empty',
      'empty_favorites_subtitle':
          'Click add button above to start exploring and choose your favorite estates.',
      'explore_estates': 'Explore Estates',
      'browse_as_guest': 'Browse as Guest',
      'recent_properties': 'Recent Properties',
      'recently_added': 'Recently added listings',
      'customers': 'Customers',
      // Categories
      'all': 'All',
      'house': 'House',
      'apartment': 'Apartment',
      'villa': 'Villa',
      'commercial': 'Commercial',
      'land': 'Land',
      'riad': 'Riad',
      'studio': 'Studio',
      'chalet': 'Chalet',
      // Alerts & Actions
      'require_login': 'Please login first',
      'cannot_buy_own': 'You cannot buy your own property.',
      'cannot_rent_own': 'You cannot rent your own property.',
      'ok': 'OK',
      'cancel': 'Cancel',
      'confirm': 'Confirm',
      'rent_property': 'Rent Property',
      'start_date': 'Start Date',
      'months': 'Months: ',
      'no_listings_found': 'No listings found',
      'no_featured_found': 'No featured properties found.',
      'no_rental_found': 'No rental properties found.',
      'no_properties_found': 'No properties found.',
      'error': 'Error: ',
      'fill_required_fields': 'Please fill all required fields',
      'change_location': 'Change location',
      'failed_avatar': 'Failed to upload avatar: ',

      // Transactions
      'buy': 'Buy Now',
      'rent_now': 'Rent Now',
      'price': 'Price',
      'status_completed': 'Completed',
      'status_canceled': 'Canceled',
      'status_pending': 'Pending',
      'status_active': 'Active',
      'update_profile_failed': 'Failed to update profile. Please try again.',
      'phone_number': 'Phone Number',
      'cost_desc_not_avail': 'Cost description not available.',
      'trans_price': 'Price:',
      'trans_seller': 'Seller',
      'trans_buyer': 'Buyer',
      'trans_owner': 'Owner',
      'trans_tenant': 'Tenant',
      'down_payment_help': 'down payment/full payment',
      'monthly_budget_help': 'your monthly budget',
      'rooms': 'Rooms',
      // Filters & Forms
      'payment_cash': 'Cash in hand',
      'payment_monthly': 'Monthly installment',
      'number_of_rooms': 'Number of rooms',
      'property_type': 'Property type',
      'property_status': 'Property status',
      'find_my_home': 'Find my home',
      'enter_location': 'Enter location',
      'house_for_sale': 'House for sale',
      'phone_number_hint': 'Phone number',
      'map_placeholder': 'Map Placeholder',
      'add_listing': 'Add Listing',
      'update_listing': 'Update Listing',
      'listing_type': 'Listing type',
      'rent_price_label': 'Rent Price (MAD/month)',
      'sell_price_label': 'Sell Price (MAD)',
      'area_label': 'Area (m²)',
      'features': 'Property Features',
      'location': 'Location',
      'listing_photos': 'Listing Photos',
      'edit_location': 'Edit location',
      'contact_info': 'Contact Information',
      'discover': 'Discover',
      'find_perfect': 'Find your perfect property',
      'sort': 'Sort',
      'sort_by': 'Sort By',
      'sort_default': 'Default',
      'sort_price_asc': 'Price: Low to High',
      'sort_price_desc': 'Price: High to Low',
      'sort_rating': 'Rating',
      'property_singular': 'Property',
      'property_plural': 'Properties',
      'no_properties_desc':
          'We couldn\'t find any properties matching\nyour search criteria.',
      'reset_filters': 'Reset Filters',
      'listing_now_published_1': 'Your listing is now\n',
      'listing_now_published_2': 'published',
      'listing_success_desc': 'Lorem ipsum dolor sit amet, consectetur.',
      'add_more': 'Add More',
      'finish': 'Finish',
      'listing_title': 'Listing Title',
      'enter_title': 'Enter listing title',
      'property_category': 'Property category',
      'for_rent': 'Rent',
      'for_sale': 'Sell',
      'bedroom': 'Bedroom',
      'balcony': 'Balcony',
      'kitchen': 'Kitchen',
      'toilet': 'Toilet',
      'living_room': 'Living Room',
      'total_rooms': 'Total Rooms',
      'environment_facilities': 'Environment / Facilities',
      'edit_phone': 'Edit Phone Number',
      'close': 'Close',
      'listing_updated_1': 'Your listing just\n',
      'listing_updated_2': 'successfuly updated',
      'trans_from': 'From:',
      'trans_to': 'To:',
      'trans_reject': 'Reject',
      'trans_accept': 'Accept',
      'trans_terminate': 'Terminate',
      'trans_no_found': 'No transactions found.',
      'my_transactions': 'My Transactions',
      'mes_achats': 'My Purchases',
      'mes_ventes': 'My Sales',
      'mes_locations': 'Rented by me (Tenant)',
      'biens_loues': 'My Rented Properties (Owner)',
      'join_darna_today': 'Join Darna Today!',
      'guest_signup_prompt':
          'Sign in or create an account to save favorites,\ncontact agents and more.',
      'browsing_as_guest': 'Browsing as Guest',
      'signin_full_access': 'Sign in for full access',
      'unlock_full_access': 'Unlock Full Access',
      'unlock_subtitle':
          'Save favorites, contact agents\nand browse all listings.',
      'signin_now': 'Sign In Now →',
    },
    'fr': {
      'welcome': 'Bienvenue chez Darna',
      'welcome_subtitle':
          'Découvrez la propriété parfaite au Maroc.\nVotre voyage vers une nouvelle maison commence ici.',
      'get_started': 'Commencer',
      'signin': 'Se connecter',
      'signup': "S'inscrire",
      'email': 'E-mail',
      'password': 'Mot de passe',
      'forgot_password': 'Mot de passe oublié ?',
      'or': 'OU',
      'dont_have_account': "Vous n'avez pas de compte ? ",
      'already_have_account': 'Vous avez déjà un compte ? ',
      'full_name': 'Nom complet',
      'phone': 'Numéro de téléphone',
      'create_account': 'Créez votre compte pour continuer',
      'account_created': 'Compte créé !',
      'welcome_darna': 'Bienvenue dans la famille Darna !',
      'profile': 'Profil',
      'edit_profile': 'Modifier le profil',
      'settings': 'Paramètres',
      'language': 'Langue',
      'dark_mode': 'Mode sombre',
      'light_mode': 'Mode clair',
      'logout': 'Déconnexion',
      'coming_soon': 'Bientôt disponible !',
      'update': 'Mettre à jour',
      'success': 'Succès',
      'profile_updated': 'Profil mis à jour avec succès !',
      'social_accounts': 'Comptes sociaux',
      'link': 'Lier',
      'unlink': 'Délier',
      'listings_count': 'Annonces',
      'sold_count': 'Vendu',
      'reviews_count': 'Avis',
      'transactions_count': 'Transactions',
      'no_sold_properties': 'Aucune propriété vendue',
      'no_sold_subtitle': 'Vos propriétés vendues apparaîtront ici',
      'hello': 'Bonjour 👋',
      'categories': 'Catégories',
      'featured_properties': 'Propriétés vedettes',
      'best_deals': 'Meilleures offres pour vous',
      'top_locations': 'Emplacements populaires',
      'explore_popular': 'Explorer les zones populaires',
      'best_for_rent': 'Meilleur à louer',
      'monthly_rental': 'Options de location mensuelle',
      'search_properties': 'Rechercher des propriétés...',
      'see_all': 'Tout voir',
      'explore': 'Explorer',
      'properties': 'Propriétés',
      'agents': 'Agents',
      'listings_suffix': 'annonces',
      // Navigation
      'nav_home': 'Accueil',
      'nav_search': 'Recherche',
      'nav_favorites': 'Favoris',
      'nav_profile': 'Profil',
      'nav_messages': 'Messages',
      // Chat
      'messages': 'Messages',
      'conversations': 'Conversations',
      'no_conversations': 'Aucune conversation',
      'no_conversations_desc':
          'Commencez à discuter en contactant un propriétaire depuis la page de détails.',
      'no_messages': 'Aucun message. Dites bonjour !',
      'type_message': 'Tapez un message...',
      'send': 'Envoyer',
      'chat_auto_message': 'Bonjour, je suis intéressé par ce bien.',
      'cannot_chat_own':
          'Vous ne pouvez pas discuter de votre propre propriété.',
      'typing': 'en train d\'écrire...',
      'online': 'En ligne',
      'last_seen': 'dernière connexion',
      'delete_for_me': 'Supprimer pour moi',
      'delete_for_everyone': 'Supprimer pour tout le monde',
      'message_deleted': 'Ce message a été supprimé',
      'recording': 'Enregistrement...',

      // Reviews & Ratings
      'leave_review': 'Laisser un avis',
      'edit_review': 'Modifier l\'avis',
      'delete_review': 'Supprimer l\'avis',
      'submit_review': 'Soumettre l\'avis',
      'review_success': 'Avis soumis avec succès',
      'review_updated_success': 'Avis mis à jour avec succès',
      'review_deleted_success': 'Avis supprimé avec succès',
      'owner_review_error':
          'Vous ne pouvez pas évaluer votre propre propriété.',
      'duplicate_review_error': 'Vous avez déjà évalué cette propriété.',
      'rating_required': 'Une note est requise (1-5 étoiles).',

      // Property Details
      'bedrooms': 'Chambres',
      'bathroom': 'Salle de bain',
      'location_facilities': 'Emplacement et installations publiques',
      'cost_of_living': 'Coût de la vie',
      'see_details': 'Voir les détails',
      'reviews': 'Avis',
      'view_all_reviews': 'Voir tous les avis',
      'view_property': 'Voir la propriété',
      'view_on_map': 'Voir sur la carte',
      'nearby_properties': 'Propriétés à proximité',
      'nearby_location': 'À proximité de cet emplacement',
      'mad': 'MAD',
      'month': 'mois',
      'drive': 'trajet',
      'map_view': 'Espace pour la carte',
      'contact_agent': 'Contacter l\'agent (Bientôt disponible)',
      'ar_view': 'Vue AR (Bientôt disponible)',
      'my_favorites': 'Mes Favoris',
      'favorites': 'Favoris',
      'favorite': 'Favori',
      'clear_all': 'Tout effacer',
      'empty_favorites_title': 'Votre page de favoris est vide',
      'empty_favorites_subtitle':
          'Cliquez sur le bouton ajouter ci-dessus pour commencer à explorer et choisir vos propriétés préférées.',
      'explore_estates': 'Explorer les propriétés',
      'browse_as_guest': 'Parcourir en tant qu\'invité',
      'recent_properties': 'Propriétés récentes',
      'recently_added': 'Annonces récemment ajoutées',
      'customers': 'Clients',
      // Categories
      'all': 'Tout',
      'house': 'Maison',
      'apartment': 'Appartement',
      'villa': 'Villa',
      'commercial': 'Commercial',
      'land': 'Terrain',
      'riad': 'Riad',
      'studio': 'Studio',
      'chalet': 'Chalet',
      // Alerts & Actions
      'require_login': 'Veuillez vous connecter d\'abord',
      'cannot_buy_own': 'Vous ne pouvez pas acheter votre propre propriété.',
      'cannot_rent_own': 'Vous ne pouvez pas louer votre propre propriété.',
      'ok': 'OK',
      'cancel': 'Annuler',
      'confirm': 'Confirmer',
      'rent_property': 'Louer la propriété',
      'start_date': 'Date de début',
      'months': 'Mois: ',
      'no_listings_found': 'Aucune annonce trouvée',
      'no_featured_found': 'Aucune propriété vedette trouvée.',
      'no_rental_found': 'Aucune propriété à louer trouvée.',
      'no_properties_found': 'Aucune propriété trouvée.',
      'error': 'Erreur: ',
      'fill_required_fields': 'Veuillez remplir tous les champs obligatoires',
      'change_location': 'Changer d\'emplacement',
      'failed_avatar': 'Échec du téléchargement de l\'avatar: ',
      // Transactions
      'buy': 'Acheter',
      'rent_now': 'Louer',
      'price': 'Prix',
      'status_completed': 'Terminé',
      'status_canceled': 'Annulé',
      'status_pending': 'En attente',
      'status_active': 'Actif',
      'update_profile_failed':
          'Échec de la mise à jour du profil. Veuillez réessayer.',
      'phone_number': 'Numéro de téléphone',
      'cost_desc_not_avail': 'Description des coûts indisponible.',
      'trans_price': 'Prix :',
      'trans_seller': 'Vendeur',
      'trans_buyer': 'Acheteur',
      'trans_owner': 'Propriétaire',
      'trans_tenant': 'Locataire',
      'down_payment_help': 'acompte/paiement intégral',
      'monthly_budget_help': 'votre budget mensuel',
      'rooms': 'Pièces',
      // Filters & Forms
      'payment_cash': 'Paiement en espèces',
      'payment_monthly': 'Paiement mensuel',
      'number_of_rooms': 'Nombre de pièces',
      'property_type': 'Type de propriété',
      'property_status': 'Statut de la propriété',
      'find_my_home': 'Trouver ma maison',
      'enter_location': 'Entrer l\'emplacement',
      'house_for_sale': 'Maison à vendre',
      'phone_number_hint': 'Numéro de téléphone',
      'map_placeholder': 'Espace carte',
      'add_listing': 'Ajouter une annonce',
      'update_listing': 'Modifier l\'annonce',
      'listing_type': 'Type d\'annonce',
      'rent_price_label': 'Prix de location (MAD/mois)',
      'sell_price_label': 'Prix de vente (MAD)',
      'area_label': 'Superficie (m²)',
      'features': 'Caractéristiques',
      'location': 'Emplacement',
      'listing_photos': 'Photos de l\'annonce',
      'edit_location': 'Modifier emplacement',
      'contact_info': 'Informations de contact',
      'discover': 'Découvrir',
      'find_perfect': 'Trouvez votre bien idéal',
      'sort': 'Trier',
      'sort_by': 'Trier par',
      'sort_default': 'Par défaut',
      'sort_price_asc': 'Prix : croissant',
      'sort_price_desc': 'Prix : décroissant',
      'sort_rating': 'Note',
      'property_singular': 'Propriété',
      'property_plural': 'Propriétés',
      'no_properties_desc': 'Aucun bien ne correspondà vos critères.',
      'reset_filters': 'Réinitialiser',
      'listing_now_published_1': 'Votre annonce est maintenant\n',
      'listing_now_published_2': 'publiée',
      'listing_success_desc': 'Félicitations pour votre nouvelle annonce.',
      'add_more': 'Ajouter plus',
      'finish': 'Terminer',
      'listing_title': 'Titre de l\'annonce',
      'enter_title': 'Entrez le titre',
      'property_category': 'Catégorie du bien',
      'for_rent': 'Location',
      'for_sale': 'Vente',
      'bedroom': 'Chambre',
      'balcony': 'Balcon',
      'kitchen': 'Cuisine',
      'toilet': 'Toilettes',
      'living_room': 'Salon',
      'total_rooms': 'Nombre total de pièces',
      'environment_facilities': 'Environnement / Équipements',
      'edit_phone': 'Modifier le téléphone',
      'close': 'Fermer',
      'listing_updated_1': 'Votre annonce vient\n',
      'listing_updated_2': 'd\'être mise à jour',
      'trans_from': 'Du :',
      'trans_to': 'Au :',
      'trans_reject': 'Refuser',
      'trans_accept': 'Accepter',
      'trans_terminate': 'Résilier',
      'trans_no_found': 'Aucune transaction trouvée.',
      'my_transactions': 'Mes Transactions',
      'mes_achats': 'Mes achats',
      'mes_ventes': 'Mes ventes',
      'mes_locations': 'Mes locations',
      'biens_loues': 'Biens loués',
      'join_darna_today': 'Rejoignez Darna aujourd\'hui !',
      'guest_signup_prompt':
          'Connectez-vous ou créez un compte pour enregistrer vos favoris,\ncontacter des agents et plus encore.',
      'browsing_as_guest': 'Navigation en tant qu\'invité',
      'signin_full_access': 'Connectez-vous pour un accès complet',
      'unlock_full_access': 'Débloquer l\'accès complet',
      'unlock_subtitle':
          'Enregistrez vos favoris, contactez des agents\net parcourez toutes les annonces.',
      'signin_now': 'Se connecter maintenant →',
    },
    'ar': {
      'welcome': 'مرحباً بكم في دارنا',
      'welcome_subtitle':
          'اكتشف العقار المثالي في المغرب.\nرحلتك إلى بيت جديد تبدأ من هنا.',
      'get_started': 'ابدأ الآن',
      'signin': 'تسجيل الدخول',
      'signup': 'إنشاء حساب',
      'email': 'البريد الإلكتروني',
      'password': 'كلمة المرور',
      'forgot_password': 'هل نسيت كلمة المرور؟',
      'or': 'أو',
      'dont_have_account': 'ليس لديك حساب؟ ',
      'already_have_account': 'لديك حساب بالفعل؟ ',
      'full_name': 'الاسم الكامل',
      'phone': 'رقم الهاتف',
      'create_account': 'أنشئ حسابك للمتابعة',
      'account_created': 'تم إنشاء الحساب!',
      'welcome_darna': 'مرحباً بك في عائلة دارنا!',
      'profile': 'الملف الشخصي',
      'edit_profile': 'تعديل الملف الشخصي',
      'settings': 'الإعدادات',
      'language': 'اللغة',
      'dark_mode': 'الوضع الليلي',
      'light_mode': 'الوضع النهاري',
      'logout': 'تسجيل الخروج',
      'coming_soon': 'قريباً!',
      'update': 'تحديث الملف',
      'success': 'نجاح',
      'profile_updated': 'تم تحديث الملف الشخصي بنجاح!',
      'social_accounts': 'الحسابات الاجتماعية',
      'link': 'ربط',
      'unlink': 'إلغاء الربط',
      'listings_count': 'العقارات',
      'sold_count': 'المباعة',
      'reviews_count': 'التقييمات',
      'transactions_count': 'المعاملات',
      'no_sold_properties': 'لا توجد عقارات مباعة',
      'no_sold_subtitle': 'عقاراتك المباعة ستظهر هنا',
      'hello': 'مرحباً 👋',
      'categories': 'الفئات',
      'featured_properties': 'عقارات مميزة',
      'best_deals': 'أفضل العروض لك',
      'top_locations': 'أفضل المواقع',
      'explore_popular': 'استكشف المناطق الشهيرة',
      'best_for_rent': 'الأفضل للإيجار',
      'monthly_rental': 'خيارات الإيجار الشهري',
      'search_properties': 'البحث عن عقارات...',
      'see_all': 'عرض الكل',
      'explore': 'استكشاف',
      'properties': 'عقارات',
      'agents': 'وكلاء',
      'listings_suffix': 'عقار',
      // Navigation
      'nav_home': 'الرئيسية',
      'nav_search': 'بحث',
      'nav_favorites': 'المفضلة',
      'nav_profile': 'حسابي',
      'nav_messages': 'الرسائل',
      // Chat
      'messages': 'الرسائل',
      'conversations': 'المحادثات',
      'no_conversations': 'لا توجد محادثات',
      'no_conversations_desc':
          'ابدأ المحادثة عبر التواصل مع مالك العقار من صفحة التفاصيل.',
      'no_messages': 'لا توجد رسائل. قل مرحبا!',
      'type_message': 'اكتب رسالة...',
      'send': 'إرسال',
      'chat_auto_message': 'سلام، أنا مهتم بهذا العقار.',
      'cannot_chat_own': 'لا يمكنك الدردشة حول عقارك الخاص.',
      'typing': 'يكتب...',
      'online': 'متصل',
      'last_seen': 'آخر ظهور',
      'delete_for_me': 'حذف عندي',
      'delete_for_everyone': 'حذف عند الجميع',
      'message_deleted': 'تم حذف هذه الرسالة',
      'recording': 'جاري التسجيل...',

      // Reviews & Ratings
      'leave_review': 'أضف تقييم',
      'edit_review': 'تعديل التقييم',
      'delete_review': 'حذف التقييم',
      'submit_review': 'إرسال التقييم',
      'review_success': 'تم إرسال التقييم بنجاح',
      'review_updated_success': 'تم تحديث التقييم بنجاح',
      'review_deleted_success': 'تم حذف التقييم بنجاح',
      'owner_review_error': 'لا يمكنك تقييم عقارك الخاص.',
      'duplicate_review_error': 'لقد قمت بتقييم هذا العقار مسبقاً.',
      'rating_required': 'يرجى تحديد تقييم من (1-5) نجوم.',

      // Property Details
      'bedrooms': 'غرف نوم',
      'bathroom': 'حمام',
      'location_facilities': 'الموقع والمرافق العامة',
      'cost_of_living': 'تكلفة المعيشة',
      'see_details': 'عرض التفاصيل',
      'reviews': 'التقييمات',
      'view_all_reviews': 'عرض كل التقييمات',
      'view_property': 'عرض العقار',
      'view_on_map': 'عرض على الخريطة',
      'nearby_properties': 'عقارات قريبة',
      'nearby_location': 'بالقرب من هذا الموقع',
      'mad': 'درهم',
      'month': 'شهر',
      'drive': 'قيادة',
      'map_view': 'خريطة',
      'contact_agent': 'اتصل بالوكيل (قريباً)',
      'ar_view': 'الواقع المعزز (قريباً)',
      'my_favorites': 'مفضلاتي',
      'favorites': 'المفضلة',
      'favorite': 'المفضلة',
      'clear_all': 'مسح الكل',
      'empty_favorites_title': 'صفحة المفضلة لديك فارغة',
      'empty_favorites_subtitle':
          'انقر فوق زر الإضافة أعلاه لبدء الاستكشاف واختيار عقاراتك المفضلة.',
      'explore_estates': 'استكشاف العقارات',
      'browse_as_guest': 'تصفح كزائر',
      'recent_properties': 'عقارات حديثة',
      'recently_added': 'أحدث الإعلانات المضافة',
      'customers': 'العملاء',
      // Categories
      'all': 'الكل',
      'house': 'منزل',
      'apartment': 'شقة',
      'villa': 'فيلا',
      'commercial': 'محل تجاري',
      'land': 'أرض',
      'riad': 'رياض',
      'studio': 'ستوديو',
      'chalet': 'شاليه',
      // Alerts & Actions
      'require_login': 'المرجو تسجيل الدخول أولاً',
      'cannot_buy_own': 'لا يمكنك شراء عقارك الخاص.',
      'cannot_rent_own': 'لا يمكنك استئجار عقارك الخاص.',
      'ok': 'حسنا',
      'cancel': 'إلغاء',
      'confirm': 'تأكيد',
      'rent_property': 'استئجار العقار',
      'start_date': 'تاريخ البدء',
      'months': 'الأشهر: ',
      'no_listings_found': 'لم يتم العثور على أي عقار',
      'no_featured_found': 'لم يتم العثور على عقارات مميزة.',
      'no_rental_found': 'لم يتم العثور على عقارات للإيجار.',
      'no_properties_found': 'لم يتم العثور على عقارات.',
      'error': 'خطأ: ',
      'fill_required_fields': 'المرجو ملء جميع الحقول الإلزامية',
      'change_location': 'تغيير الموقع',
      'failed_avatar': 'فشل تحميل الصورة الشخصية: ',
      // Transactions
      'buy': 'شراء',
      'rent_now': 'استئجار',
      'price': 'السعر',
      'status_completed': 'مكتمل',
      'status_canceled': 'ملغى',
      'status_pending': 'قيد الانتظار',
      'status_active': 'نشط',
      'update_profile_failed':
          'فشل تحديث الملف الشخصي. يرجى المحاولة مرة أخرى.',
      'phone_number': 'رقم الهاتف',
      'cost_desc_not_avail': 'وصف التكلفة غير متوفر.',
      'trans_price': 'السعر:',
      'trans_seller': 'البائع',
      'trans_buyer': 'المشتري',
      'trans_owner': 'المالك',
      'trans_tenant': 'المكتري',
      'down_payment_help': 'دفعة أولى/الدفع الكامل',
      'monthly_budget_help': 'ميزانيتك الشهرية',
      'rooms': 'غرف',
      // Filters & Forms
      'payment_cash': 'دفع نقداً',
      'payment_monthly': 'دفعات شهرية',
      'number_of_rooms': 'عدد الغرف',
      'property_type': 'نوع العقار',
      'property_status': 'حالة العقار',
      'find_my_home': 'ابحث عن بيتي',
      'enter_location': 'أدخل الموقع',
      'house_for_sale': 'منزل للبيع',
      'phone_number_hint': 'رقم الهاتف',
      'map_placeholder': 'مكان الخريطة',
      'add_listing': 'أضف إعلان',
      'update_listing': 'تحديث الإعلان',
      'listing_type': 'نوع الإعلان',
      'rent_price_label': 'سعر الإيجار (درهم/شهر)',
      'sell_price_label': 'سعر البيع (درهم)',
      'area_label': 'المساحة (م²)',
      'features': 'مميزات العقار',
      'location': 'الموقع',
      'listing_photos': 'صور الإعلان',
      'edit_location': 'تعديل الموقع',
      'contact_info': 'معلومات التواصل',
      'discover': 'اكتشف',
      'find_perfect': 'ابحث عن عقارك المثالي',
      'sort': 'ترتيب',
      'sort_by': 'ترتيب حسب',
      'sort_default': 'الافتراضي',
      'sort_price_asc': 'السعر: من الأقل للأعلى',
      'sort_price_desc': 'السعر: من الأعلى للأقل',
      'sort_rating': 'التقييم',
      'property_singular': 'عقار',
      'property_plural': 'عقارات',
      'no_properties_desc': 'لم نجد أي عقار يطابق بحثك.',
      'reset_filters': 'إعادة تعيين',
      'listing_now_published_1': 'إعلانك الآن\n',
      'listing_now_published_2': 'منشور',
      'listing_success_desc': 'تهانينا على نشر الإعلان بنجاح.',
      'add_more': 'أضف المزيد',
      'finish': 'إنهاء',
      'listing_title': 'عنوان الإعلان',
      'enter_title': 'أدخل عنوان الإعلان',
      'property_category': 'فئة العقار',
      'for_rent': 'إيجار',
      'for_sale': 'بيع',
      'bedroom': 'غرفة النوم',
      'balcony': 'شرفة',
      'kitchen': 'مطبخ',
      'toilet': 'دورة المياه',
      'living_room': 'غرفة المعيشة',
      'total_rooms': 'مجموع الغرف',
      'environment_facilities': 'البيئة / المرافق',
      'edit_phone': 'تعديل رقم الهاتف',
      'close': 'إغلاق',
      'listing_updated_1': 'تم تحديث\n',
      'listing_updated_2': 'إعلانك بنجاح',
      'trans_from': 'من:',
      'trans_to': 'إلى:',
      'trans_reject': 'رفض',
      'trans_accept': 'قبول',
      'trans_terminate': 'إنهاء',
      'trans_no_found': 'لا توجد معاملات.',
      'my_transactions': 'معاملاتي',
      'mes_achats': 'مشترياتي',
      'mes_ventes': 'مبيعاتي',
      'mes_locations': 'إيجاراتي',
      'biens_loues': 'عقاراتي المؤجرة',
      'join_darna_today': 'انضم إلى دارنا اليوم!',
      'guest_signup_prompt':
          'سجل الدخول أو أنشئ حساباً لحفظ مفضلاتك،\nوالتواصل مع الوكلاء والمزيد.',
      'browsing_as_guest': 'تصفح كزائر',
      'signin_full_access': 'سجل الدخول للوصول الكامل',
      'unlock_full_access': 'استفد من الوصول الكامل',
      'unlock_subtitle':
          'احفظ مفضلاتك، تواصل مع الوكلاء\nوتصفح جميع الإعلانات.',
      'signin_now': 'سجل الدخول الآن ←',
    },
  };

  void setLanguage(String languageCode) async {
    _locale = Locale(languageCode);
    notifyListeners();
    final prefs = await SharedPreferences.getInstance();
    await prefs.setString('language_code', languageCode);
  }

  void _loadLanguage() async {
    final prefs = await SharedPreferences.getInstance();
    final languageCode = prefs.getString('language_code') ?? 'en';
    _locale = Locale(languageCode);
    _isLoading = false;
    notifyListeners();
  }

  String translate(String key) {
    return _translations[_locale.languageCode]?[key] ?? key;
  }
}

extension LocalizationExtension on BuildContext {
  String tr(String key) =>
      Provider.of<LanguageProvider>(this, listen: false).translate(key);
}
