import 'package:flutter/material.dart';
import 'package:provider/provider.dart';
import 'package:shared_preferences/shared_preferences.dart';
import '../navigation/app_router.dart';

class LanguageProvider with ChangeNotifier {
  Locale _locale = const Locale('en');
  bool _isLoading = true;

  Locale get locale => _locale;
  bool get isLoading => _isLoading;
  bool get isArabic => _locale.languageCode == 'ar';

  LanguageProvider() {
    _loadLanguage();
  }

  void toggleLanguage() {
    final newLanguage = _locale.languageCode == 'ar'
        ? 'en'
        : (_locale.languageCode == 'en' ? 'fr' : 'en');
    setLanguage(newLanguage);
  }

  static final Map<String, Map<String, String>> _translations = {
    'en': {
      'welcome': 'Welcome to Darna',
      'welcome_subtitle':
          'Discover the perfect property in Morocco.\nYour journey to a new home starts here.',
      'get_started': 'Get Started',
      'signin': 'Sign In',
      'signup': 'Sign Up',
      'email': 'Email',
      'password': 'Password',
      'forgot_password': 'Forgot Password?',
      'or': 'OR',
      'dont_have_account': "Don't have an account? ",
      'already_have_account': 'Already have an account? ',
      'full_name': 'Full Name',
      'phone': 'Phone Number',
      'create_account': 'Create your account to continue',
      'account_created': 'Account Created!',
      'welcome_darna': 'Welcome to the Darna family!',
      'profile': 'Profile',
      'edit_profile': 'Edit Profile',
      'settings': 'Settings',
      'language': 'Language',
      'dark_mode': 'Dark Mode',
      'light_mode': 'Light Mode',
      'logout': 'Logout',
      'coming_soon': 'Coming Soon!',
      'update': 'Update Profile',
      'success': 'Success',
      'profile_updated': 'Profile updated successfully!',
      'social_accounts': 'Social Accounts',
      'link': 'Link',
      'unlink': 'Unlink',
      'listings_count': 'Listings',
      'sold_count': 'Sold',
      'reviews_count': 'Reviews',
      'transactions_count': 'Transactions',
      'no_sold_properties': 'No Sold Properties',
      'no_sold_subtitle': 'Your sold properties will appear here',
      'hello': 'Hello 👋',
      'categories': 'Categories',
      'featured_properties': 'Featured Properties',
      'best_deals': 'Best deals for you',
      'top_locations': 'Top Locations',
      'explore_popular': 'Explore popular areas',
      'best_for_rent': 'Best For Rent',
      'monthly_rental': 'Monthly rental properties',
      'best_for_sale': 'Best For Sale',
      'properties_for_sale': 'Properties available to buy',
      'no_sale_found': 'No properties found for sale',
      'search_properties': 'Search properties...',
      'see_all': 'See All',
      'explore': 'Explore',
      'properties': 'Properties',
      'agents': 'Agents',
      'listings_suffix': 'listings',
      'no_notifications': 'No notifications yet',
      'no_notifications_desc': 'When you get notifications, they\'ll show up here',
      // Navigation
      'nav_home': 'Home',
      'nav_search': 'Search',
      'nav_favorites': 'Favorites',
      'nav_profile': 'Profile',
      'nav_messages': 'Messages',
      // Chat
      'messages': 'Messages',
      'conversations': 'Conversations',
      'no_conversations': 'No conversations yet',
      'no_conversations_desc':
          'Start chatting by contacting a property owner from the property details page.',
      'no_messages': 'No messages yet. Say hello!',
      'type_message': 'Type a message...',
      'send': 'Send',
      'chat_auto_message': 'Salam, I am interested in this property.',
      'cannot_chat_own':
          'You cannot chat with yourself about your own property.',
      'typing': 'typing...',
      'online': 'Online',
      'last_seen': 'last seen',
      'delete_for_me': 'Delete for me',
      'delete_for_everyone': 'Delete for everyone',
      'message_deleted': 'This message was deleted',
      'recording': 'Recording...',

      // Reviews & Ratings
      'leave_review': 'Leave a Review',
      'edit_review': 'Edit Review',
      'delete_review': 'Delete Review',
      'submit_review': 'Submit Review',
      'review_success': 'Review submitted successfully',
      'review_updated_success': 'Review updated successfully',
      'review_deleted_success': 'Review deleted successfully',
      'owner_review_error': 'You cannot review your own property.',
      'duplicate_review_error': 'You have already reviewed this property.',
      'rating_required': 'Rating is required (1-5 stars).',

      // Property Details
      'bedrooms': 'Bedrooms',
      'bathroom': 'Bathroom',
      'location_facilities': 'Location & Public Facilities',
      'cost_of_living': 'Cost of Living',
      'see_details': 'See details',
      'reviews': 'Reviews',
      'view_all_reviews': 'View all reviews',
      'view_property': 'View Property',
      'view_on_map': 'View on Map',
      'nearby_properties': 'Nearby Properties',
      'nearby_location': 'Nearby From this Location',
      'mad': 'MAD',
      'month': 'month',
      'drive': 'drive',
      'map_view': 'Map View Placeholder',
      'contact_agent': 'Contact Agent (Coming Soon)',
      'ar_view': 'AR View (Coming Soon)',
      'my_favorites': 'My Favorites',
      'favorites': 'Favorites',
      'favorite': 'Favorite',
      'clear_all': 'Clear All',
      'empty_favorites_title': 'Your favorite page is empty',
      'empty_favorites_subtitle':
          'Click add button above to start exploring and choose your favorite estates.',
      'explore_estates': 'Explore Estates',
      'browse_as_guest': 'Browse as Guest',
      'recent_properties': 'Recent Properties',
      'recently_added': 'Recently added listings',
      'customers': 'Customers',
      // Categories
      'all': 'All',
      'house': 'House',
      'apartment': 'Apartment',
      'villa': 'Villa',
      'commercial': 'Commercial',
      'land': 'Land',
      'riad': 'Riad',
      'studio': 'Studio',
      'chalet': 'Chalet',
      // Alerts & Actions
      'require_login': 'Please login first',
      'cannot_buy_own': 'You cannot buy your own property.',
      'cannot_rent_own': 'You cannot rent your own property.',
      'ok': 'OK',
      'cancel': 'Cancel',
      'confirm': 'Confirm',
      'rent_property': 'Rent Property',
      'start_date': 'Start Date',
      'months': 'Months: ',
      'no_listings_found': 'No listings found',
      'no_featured_found': 'No featured properties found.',
      'no_rental_found': 'No rental properties found.',
      'no_properties_found': 'No properties found.',
      'error': 'Error: ',
      'fill_required_fields': 'Please fill all required fields',
      'change_location': 'Change location',
      'failed_avatar': 'Failed to upload avatar: ',

      // Transactions
      'buy': 'Buy Now',
      'rent_now': 'Rent Now',
      'price': 'Price',
      'status_completed': 'Completed',
      'status_canceled': 'Canceled',
      'status_pending': 'Pending',
      'status_active': 'Active',
      'update_profile_failed': 'Failed to update profile. Please try again.',
      'phone_number': 'Phone Number',
      'cost_desc_not_avail': 'Cost description not available.',
      'trans_price': 'Price:',
      'trans_seller': 'Seller',
      'trans_buyer': 'Buyer',
      'trans_owner': 'Owner',
      'trans_tenant': 'Tenant',
      'down_payment_help': 'down payment/full payment',
      'monthly_budget_help': 'your monthly budget',
      'rooms': 'Rooms',
      // Filters & Forms
      'payment_cash': 'Cash in hand',
      'payment_monthly': 'Monthly installment',
      'number_of_rooms': 'Number of rooms',
      'property_type': 'Property type',
      'property_status': 'Property status',
      'find_my_home': 'Find my home',
      'enter_location': 'Enter location',
      'house_for_sale': 'House for sale',
      'phone_number_hint': 'Phone number',
      'map_placeholder': 'Map Placeholder',
      'add_listing': 'Add Listing',
      'update_listing': 'Update Listing',
      'listing_type': 'Listing type',
      'rent_price_label': 'Rent Price (MAD/month)',
      'sell_price_label': 'Sell Price (MAD)',
      'area_label': 'Area (m²)',
      'features': 'Property Features',
      'location': 'Location',
      'listing_photos': 'Listing Photos',
      'edit_location': 'Edit location',
      'contact_info': 'Contact Information',
      'discover': 'Discover',
      'find_perfect': 'Find your perfect property',
      'sort': 'Sort',
      'sort_by': 'Sort By',
      'sort_default': 'Default',
      'sort_price_asc': 'Price: Low to High',
      'sort_price_desc': 'Price: High to Low',
      'sort_rating': 'Rating',
      'property_singular': 'Property',
      'property_plural': 'Properties',
      'no_properties_desc':
          'We couldn\'t find any properties matching\nyour search criteria.',
      'reset_filters': 'Reset Filters',
      'listing_now_published_1': 'Your listing is now\n',
      'listing_now_published_2': 'published',
      'listing_success_desc': 'Lorem ipsum dolor sit amet, consectetur.',
      'add_more': 'Add More',
      'finish': 'Finish',
      'listing_title': 'Listing Title',
      'enter_title': 'Enter listing title',
      'property_category': 'Property category',
      'for_rent': 'Rent',
      'for_sale': 'Sell',
      'bedroom': 'Bedroom',
      'balcony': 'Balcony',
      'kitchen': 'Kitchen',
      'toilet': 'Toilet',
      'living_room': 'Living Room',
      'total_rooms': 'Total Rooms',
      'environment_facilities': 'Environment / Facilities',
      'edit_phone': 'Edit Phone Number',
      'close': 'Close',
      'listing_updated_1': 'Your listing just\n',
      'listing_updated_2': 'successfuly updated',
      'trans_from': 'From:',
      'trans_to': 'To:',
      'trans_reject': 'Reject',
      'trans_accept': 'Accept',
      'trans_terminate': 'Terminate',
      'trans_no_found': 'No transactions found.',
      'my_transactions': 'My Transactions',
      'mes_achats': 'My Purchases',
      'mes_ventes': 'My Sales',
      'mes_locations': 'Rented by me (Tenant)',
      'biens_loues': 'My Rented Properties (Owner)',
      'join_darna_today': 'Join Darna Today!',
      'guest_signup_prompt':
          'Sign in or create an account to save favorites,\ncontact agents and more.',
      'browsing_as_guest': 'Browsing as Guest',
      'signin_full_access': 'Sign in for full access',
      'unlock_full_access': 'Unlock Full Access',
      'unlock_subtitle':
          'Save favorites, contact agents\nand browse all listings.',
      'signin_now': 'Sign In Now →',
      // Property Request
      'request_visit': 'Request a Visit',
      'request_type': 'Request Type',
      'preferred_date': 'Preferred Date',
      'preferred_time': 'Preferred Time',
      'message_optional': 'Message (optional)',
      'submit_request': 'Send Request',
      'visit': 'Schedule a Visit',
      'rent_interest': 'Interested in Renting',
      'buy_interest': 'Interested in Buying',
      'cannot_request_own': 'You cannot request your own property.',
      'comment': 'Write your comment...',
      'my_requests': 'My Requests',
      'sent_requests': 'Sent',
      'received_requests': 'Received',
      'accept': 'Accept',
      'reject': 'Reject',
      'no_requests': 'No requests found',
      'error_loading_requests': 'Failed to load requests',
      // Admin Dashboard
      'admin_dashboard': 'Admin Dashboard',
      'admin_subtitle': 'Review and manage submitted properties',
      'pending': 'Pending',
      'published': 'Published',
      'rejected': 'Rejected',
      'property_approved': 'Property approved',
      'property_rejected': 'Property rejected',
      'reject_property': 'Reject Property',
      'reject_reason': 'Reason for rejection...',
      'view': 'View',
      'approve': 'Approve',
      'no_properties_status': 'No %s properties',
      'untitled': 'Untitled',
      'unknown_owner': 'Unknown',
      'admin_dashboard_tab': 'Dashboard',
      'notifications': 'Notifications',
      'mark_all_read': 'Mark all as read',
      // Add Listing Screen
      'step_x_of_y': 'Step %s of %s',
      'fill_details_title': 'Fill detail of your',
      'real_estate': 'real estate',
      'where_is_location': 'Where is the',
      'location_question': 'location',
      'add_photos_title': 'Add',
      'photos_word': 'photos',
      'to_your_listing': 'to your listing',
      'almost_finish': 'Almost finish',
      'complete_listing': ', complete the listing',
      'review_word': 'Review',
      'your_listing': 'your listing',
      'review_subtitle': 'Make sure everything looks good before publishing.',
      'next': 'Next',
      'submit_for_review': 'Submit for Review',
      'rent_price_month': 'Rent Price / Month',
      'sell_price': 'Sell Price',
      'title_label': 'Title',
      'type_label': 'Type',
      'photos_label': 'Photos',
      'photo_count': 'photo(s)',
      'rooms_summary': 'bed',
      'bath_summary': 'bath',
      'balcony_summary': 'balcony',
      'kitchen_summary': 'kitchen',
      'facilities_label': 'Facilities',
      'submitted_for_review': 'Your listing has been\nsubmitted for review',
      'submitted_review_desc': 'Our team will review your property and publish it shortly. You can track its status in My Listings.',
      'parking_lot': 'Parking Lot',
      'pet_allowed': 'Pet Allowed',
      'garden': 'Garden',
      'gym': 'Gym',
      'park': 'Park',
      'home_theatre': 'Home Theatre',
      'kids_friendly': 'Kid\'s Friendly',
      'wifi': 'WIFI',
      // Verify Email Screen
      'verify_email': 'Verify Email',
      'check_your_email': 'Check your email',
      'verification_sent': 'We have sent a 6-digit verification code to',
      'verify': 'Verify',
      'didnt_receive': 'Didn\'t receive the code? ',
      'resend_in': 'Resend in',
      'resend': 'Resend',
      'code_resent': 'Verification code resent.',
      // Forgot Password Screen
      'forgot_password_title': 'Forgot Password',
      'reset_password': 'Reset Password',
      'reset_password_desc': 'Enter the email address associated with your account and we\'ll send you a 6-digit code to reset your password.',
      'send_code': 'Send Code',
      'enter_code_title': 'Enter Code',
      'code_sent_to': 'We sent a 6-digit code to',
      'code_sent_suffix': '. Enter it below along with your new password.',
      'digit_code': '6-digit Code',
      'new_password': 'New Password',
      'confirm_password': 'Confirm Password',
      'valid_email_error': 'Please enter a valid email address',
      'code_digits_error': 'Code must be 6 digits',
      'password_length_error': 'Password must be at least 8 characters',
      'passwords_match_error': 'Passwords do not match',
      'password_reset_success': 'Password reset successfully! Please sign in.',
      // General & Call & Requests
      'failed_to_update_request_status': 'Failed to update request status',
      'no_requests': 'No requests found',
      'decline': 'Decline',
      'accept': 'Accept',
      'call_ended': 'Call ended',
      'location_not_set': 'Location not set',
      'tap_for_directions': 'Tap for directions',
      'request_visit': 'Request Visit',
      'request_type': 'Request Type',
      'submit_request': 'Submit Request',
      'owner_not_found': 'Owner not found',
      'no_notifications_yet': 'No notifications yet',
      'no_properties_found': 'No properties found',
      'status_published': 'Published',
      'status_available': 'Available',
      'status_hidden': 'Hidden',
      'status_rejected': 'Rejected',
      'status_pending': 'Pending',
      'status_accepted': 'Accepted',
      'status_completed': 'Completed',
      'request_type_visit': 'Visit',
      'request_updated_success': 'Request updated successfully',
      'verification_failed': 'Verification failed: ',
      'error_prefix': 'Error: ',
      'google_signin_failed': 'Google Sign-In failed: ',
      'from': 'From: ',
      'to': 'To: ',
      'user': 'User',
      'enable_location': 'Enable location',
      'to_see_distance': 'to see distance',
      'min_drive': 'min drive',
      'h_drive': 'h drive',
      'unknown_agent': 'Unknown Agent',
      'property_owner': 'Property Owner',
      'unknown_location': 'Unknown location',
      'unknown_property': 'Unknown Property',
      'no_title': 'No title',
      'logout_confirm': 'Are you sure you want to logout?',
      'cancel': 'Cancel',
      'coming_soon_feature': 'Coming Soon',
      'request_sent_success': 'Request sent successfully.',
      'calling': 'Calling...',
      'property': 'Property',
      'per_month': '/month',
      'delete_property': 'Delete Property',
      'delete_property_confirm': 'Are you sure you want to permanently delete this property?',
      'delete': 'Delete',
      'enable': 'Enable',
      'disable': 'Disable',
      // Admin Categories
      'categories_tab': 'Categories',
      'manage_categories': 'Manage Categories',
      'manage_categories_desc': 'Add, edit, or remove property categories',
      'add_category': 'Add Category',
      'edit_category': 'Edit Category',
      'category_name_hint': 'e.g. Apartment, Villa...',
      'category_created': 'Category created successfully',
      'category_updated': 'Category updated successfully',
      'category_deleted': 'Category deleted successfully',
      'save_changes': 'Save Changes',
      'create': 'Create',
      'delete_category': 'Delete Category',
      'confirm_delete_category': 'Are you sure you want to delete "%s"?',
      'category_has_properties': 'Cannot delete "%n". It is used by %s properties.',
      'no_categories': 'No categories found',
      'add_first_category': 'Add your first category',
      'properties_count': 'properties',
      'category.apartment': 'Apartment',
      'category.villa': 'Villa',
      'category.studio': 'Studio',
      'category.house': 'House',
      'category.commercial': 'Commercial',
      'category.riad': 'Riad',
      'category.chalet': 'Chalet',
      'category.land': 'Land',
      'all': 'All',
      'agents': 'Agents',
      'categories': 'Categories',
      'language_english': 'English',
      'language_french': 'Français',
      'map_web_only': 'Map view is only supported on web currently.',
      'unsupported_platform': 'Unsupported Platform',
      'internal_key_optional': 'Internal Key (Optional)',
      'status_all': 'All',
      'status_available': 'Available',
      'status_sold': 'Sold/Rented',
      'status_offplan': 'Offplan',
      'delete_property': 'Delete Property',
      'delete_property_confirm': 'Are you sure you want to permanently delete this property?',
      'cancel': 'Cancel',
      'delete': 'Delete',
      'error_prefix': 'Error: ',
      'status_hidden': 'Hidden',
      'status_published': 'Published',
      'status_pending': 'Pending',
      'status_rejected': 'Rejected',
      'enable': 'Enable',
      'disable': 'Disable',
      'verification_failed': 'Verification Failed: ',
      'fill_required_fields': 'Please fill all required fields',
      'error_loading_requests': 'Failed to load requests',
      'request_updated_success': 'Request updated successfully',
      'failed_to_update_request_status': 'Failed to update request status',
      'error': 'Error',
      'location': 'Location',
      'calculating': 'Calculating...',
      'status_accepted': 'Accepted',
      'status_completed': 'Completed',
      'request_type_visit': 'Visit',
      'request_type_info': 'Info',
      'request_type_offer': 'Offer',
      'at_time': 'at',
      'reject': 'Reject',
      'accept': 'Accept',
      'ar_view': 'AR View',
      'status_updated': 'Status updated',
      'location_disabled': 'Location services are disabled.',
      'location_denied': 'Location permissions are denied.',
      'location_denied_forever': 'Location permissions are permanently denied.',
      'map_clean': 'Clean',
      'map_satellite': 'Satellite',
      'all_morocco': 'All Morocco',
      'search_location': 'Search location...',
    },
    'fr': {
      'welcome': 'Bienvenue chez Darna',
      'welcome_subtitle':
          'Découvrez la propriété parfaite au Maroc.\nVotre voyage vers une nouvelle maison commence ici.',
      'get_started': 'Commencer',
      'signin': 'Se connecter',
      'signup': "S'inscrire",
      'email': 'E-mail',
      'password': 'Mot de passe',
      'forgot_password': 'Mot de passe oublié ?',
      'or': 'OU',
      'dont_have_account': "Vous n'avez pas de compte ? ",
      'already_have_account': 'Vous avez déjà un compte ? ',
      'full_name': 'Nom complet',
      'phone': 'Numéro de téléphone',
      'create_account': 'Créez votre compte pour continuer',
      'account_created': 'Compte créé !',
      'welcome_darna': 'Bienvenue dans la famille Darna !',
      'profile': 'Profil',
      'edit_profile': 'Modifier le profil',
      'settings': 'Paramètres',
      'language': 'Langue',
      'dark_mode': 'Mode sombre',
      'light_mode': 'Mode clair',
      'logout': 'Déconnexion',
      'coming_soon': 'Bientôt disponible !',
      'update': 'Mettre à jour',
      'success': 'Succès',
      'profile_updated': 'Profil mis à jour avec succès !',
      'social_accounts': 'Comptes sociaux',
      'link': 'Lier',
      'unlink': 'Délier',
      'listings_count': 'Annonces',
      'sold_count': 'Vendu',
      'reviews_count': 'Avis',
      'transactions_count': 'Transactions',
      'no_sold_properties': 'Aucune propriété vendue',
      'no_sold_subtitle': 'Vos propriétés vendues apparaîtront ici',
      'hello': 'Bonjour 👋',
      'categories': 'Catégories',
      'featured_properties': 'Propriétés vedettes',
      'best_deals': 'Meilleures offres pour vous',
      'top_locations': 'Emplacements populaires',
      'explore_popular': 'Explorer les zones populaires',
      'best_for_rent': 'Meilleur à louer',
      'monthly_rental': 'Options de location mensuelle',
      'best_for_sale': 'Meilleur à vendre',
      'properties_for_sale': 'Propriétés disponibles à l\'achat',
      'no_sale_found': 'Aucune propriété trouvée à vendre',
      'search_properties': 'Rechercher des propriétés...',
      'see_all': 'Tout voir',
      'explore': 'Explorer',
      'properties': 'Propriétés',
      'agents': 'Agents',
      'listings_suffix': 'annonces',
      'no_notifications': 'Aucune notification',
      'no_notifications_desc': 'Lorsque vous recevrez des notifications, elles apparaîtront ici',
      // Navigation
      'nav_home': 'Accueil',
      'nav_search': 'Recherche',
      'nav_favorites': 'Favoris',
      'nav_profile': 'Profil',
      'nav_messages': 'Messages',
      // Chat
      'messages': 'Messages',
      'conversations': 'Conversations',
      'no_conversations': 'Aucune conversation',
      'no_conversations_desc':
          'Commencez à discuter en contactant un propriétaire depuis la page de détails.',
      'no_messages': 'Aucun message. Dites bonjour !',
      'type_message': 'Tapez un message...',
      'send': 'Envoyer',
      'chat_auto_message': 'Bonjour, je suis intéressé par ce bien.',
      'cannot_chat_own':
          'Vous ne pouvez pas discuter de votre propre propriété.',
      'typing': 'en train d\'écrire...',
      'online': 'En ligne',
      'last_seen': 'dernière connexion',
      'delete_for_me': 'Supprimer pour moi',
      'delete_for_everyone': 'Supprimer pour tout le monde',
      'message_deleted': 'Ce message a été supprimé',
      'recording': 'Enregistrement...',

      // Reviews & Ratings
      'leave_review': 'Laisser un avis',
      'edit_review': 'Modifier l\'avis',
      'delete_review': 'Supprimer l\'avis',
      'submit_review': 'Soumettre l\'avis',
      'review_success': 'Avis soumis avec succès',
      'review_updated_success': 'Avis mis à jour avec succès',
      'review_deleted_success': 'Avis supprimé avec succès',
      'owner_review_error':
          'Vous ne pouvez pas évaluer votre propre propriété.',
      'duplicate_review_error': 'Vous avez déjà évalué cette propriété.',
      'rating_required': 'Une note est requise (1-5 étoiles).',

      // Property Details
      'bedrooms': 'Chambres',
      'bathroom': 'Salle de bain',
      'location_facilities': 'Emplacement et installations publiques',
      'cost_of_living': 'Coût de la vie',
      'see_details': 'Voir les détails',
      'reviews': 'Avis',
      'view_all_reviews': 'Voir tous les avis',
      'view_property': 'Voir la propriété',
      'view_on_map': 'Voir sur la carte',
      'nearby_properties': 'Propriétés à proximité',
      'nearby_location': 'À proximité de cet emplacement',
      'mad': 'MAD',
      'month': 'mois',
      'drive': 'trajet',
      'map_view': 'Espace pour la carte',
      'contact_agent': 'Contacter l\'agent (Bientôt disponible)',
      'ar_view': 'Vue AR (Bientôt disponible)',
      'my_favorites': 'Mes Favoris',
      'favorites': 'Favoris',
      'favorite': 'Favori',
      'clear_all': 'Tout effacer',
      'empty_favorites_title': 'Votre page de favoris est vide',
      'empty_favorites_subtitle':
          'Cliquez sur le bouton ajouter ci-dessus pour commencer à explorer et choisir vos propriétés préférées.',
      'explore_estates': 'Explorer les propriétés',
      'browse_as_guest': 'Parcourir en tant qu\'invité',
      'recent_properties': 'Propriétés récentes',
      'recently_added': 'Annonces récemment ajoutées',
      'customers': 'Clients',
      // Categories
      'all': 'Tout',
      'house': 'Maison',
      'apartment': 'Appartement',
      'villa': 'Villa',
      'commercial': 'Commercial',
      'land': 'Terrain',
      'riad': 'Riad',
      'studio': 'Studio',
      'chalet': 'Chalet',
      // Alerts & Actions
      'require_login': 'Veuillez vous connecter d\'abord',
      'cannot_buy_own': 'Vous ne pouvez pas acheter votre propre propriété.',
      'cannot_rent_own': 'Vous ne pouvez pas louer votre propre propriété.',
      'ok': 'OK',
      'cancel': 'Annuler',
      'confirm': 'Confirmer',
      'rent_property': 'Louer la propriété',
      'start_date': 'Date de début',
      'months': 'Mois: ',
      'no_listings_found': 'Aucune annonce trouvée',
      'no_featured_found': 'Aucune propriété vedette trouvée.',
      'no_rental_found': 'Aucune propriété à louer trouvée.',
      'no_properties_found': 'Aucune propriété trouvée.',
      'error': 'Erreur: ',
      'fill_required_fields': 'Veuillez remplir tous les champs obligatoires',
      'change_location': 'Changer d\'emplacement',
      'failed_avatar': 'Échec du téléchargement de l\'avatar: ',
      // Transactions
      'buy': 'Acheter',
      'rent_now': 'Louer',
      'price': 'Prix',
      'status_completed': 'Terminé',
      'status_canceled': 'Annulé',
      'status_pending': 'En attente',
      'status_active': 'Actif',
      'update_profile_failed':
          'Échec de la mise à jour du profil. Veuillez réessayer.',
      'phone_number': 'Numéro de téléphone',
      'cost_desc_not_avail': 'Description des coûts indisponible.',
      'trans_price': 'Prix :',
      'trans_seller': 'Vendeur',
      'trans_buyer': 'Acheteur',
      'trans_owner': 'Propriétaire',
      'trans_tenant': 'Locataire',
      'down_payment_help': 'acompte/paiement intégral',
      'monthly_budget_help': 'votre budget mensuel',
      'rooms': 'Pièces',
      // Filters & Forms
      'payment_cash': 'Paiement en espèces',
      'payment_monthly': 'Paiement mensuel',
      'number_of_rooms': 'Nombre de pièces',
      'property_type': 'Type de propriété',
      'property_status': 'Statut de la propriété',
      'find_my_home': 'Trouver ma maison',
      'enter_location': 'Entrer l\'emplacement',
      'house_for_sale': 'Maison à vendre',
      'phone_number_hint': 'Numéro de téléphone',
      'map_placeholder': 'Espace carte',
      'add_listing': 'Ajouter une annonce',
      'update_listing': 'Modifier l\'annonce',
      'listing_type': 'Type d\'annonce',
      'rent_price_label': 'Prix de location (MAD/mois)',
      'sell_price_label': 'Prix de vente (MAD)',
      'area_label': 'Superficie (m²)',
      'features': 'Caractéristiques',
      'location': 'Emplacement',
      'listing_photos': 'Photos de l\'annonce',
      'edit_location': 'Modifier emplacement',
      'contact_info': 'Informations de contact',
      'discover': 'Découvrir',
      'find_perfect': 'Trouvez votre bien idéal',
      'sort': 'Trier',
      'sort_by': 'Trier par',
      'sort_default': 'Par défaut',
      'sort_price_asc': 'Prix : croissant',
      'sort_price_desc': 'Prix : décroissant',
      'sort_rating': 'Note',
      'property_singular': 'Propriété',
      'property_plural': 'Propriétés',
      'no_properties_desc': 'Aucun bien ne correspondà vos critères.',
      'reset_filters': 'Réinitialiser',
      'listing_now_published_1': 'Votre annonce est maintenant\n',
      'listing_now_published_2': 'publiée',
      'listing_success_desc': 'Félicitations pour votre nouvelle annonce.',
      'add_more': 'Ajouter plus',
      'finish': 'Terminer',
      'listing_title': 'Titre de l\'annonce',
      'enter_title': 'Entrez le titre',
      'property_category': 'Catégorie du bien',
      'for_rent': 'Location',
      'for_sale': 'Vente',
      'bedroom': 'Chambre',
      'balcony': 'Balcon',
      'kitchen': 'Cuisine',
      'toilet': 'Toilettes',
      'living_room': 'Salon',
      'total_rooms': 'Nombre total de pièces',
      'environment_facilities': 'Environnement / Équipements',
      'edit_phone': 'Modifier le téléphone',
      'close': 'Fermer',
      'listing_updated_1': 'Votre annonce vient\n',
      'listing_updated_2': 'd\'être mise à jour',
      'trans_from': 'Du :',
      'trans_to': 'Au :',
      'trans_reject': 'Refuser',
      'trans_accept': 'Accepter',
      'trans_terminate': 'Résilier',
      'trans_no_found': 'Aucune transaction trouvée.',
      'my_transactions': 'Mes Transactions',
      'mes_achats': 'Mes achats',
      'mes_ventes': 'Mes ventes',
      'mes_locations': 'Mes locations',
      'biens_loues': 'Biens loués',
      'join_darna_today': 'Rejoignez Darna aujourd\'hui !',
      'guest_signup_prompt':
          'Connectez-vous ou créez un compte pour enregistrer vos favoris,\ncontacter des agents et plus encore.',
      'browsing_as_guest': 'Navigation en tant qu\'invité',
      'signin_full_access': 'Connectez-vous pour un accès complet',
      'unlock_full_access': 'Débloquer l\'accès complet',
      'unlock_subtitle':
          'Enregistrez vos favoris, contactez des agents\net parcourez toutes les annonces.',
      'signin_now': 'Se connecter maintenant →',
      // Property Request
      'request_visit': 'Demander une visite',
      'request_type': 'Type de demande',
      'preferred_date': 'Date souhaitée',
      'preferred_time': 'Heure souhaitée',
      'message_optional': 'Message (optionnel)',
      'submit_request': 'Envoyer la demande',
      'visit': 'Planifier une visite',
      'rent_interest': 'Intéressé(e) pour louer',
      'buy_interest': 'Intéressé(e) pour acheter',
      'cannot_request_own': 'Vous ne pouvez pas faire une demande sur votre propre bien.',
      'comment': 'Rédigez votre commentaire...',
      'my_requests': 'Mes demandes',
      'sent_requests': 'Envoyées',
      'received_requests': 'Reçues',
      'accept': 'Accepter',
      'reject': 'Refuser',
      'no_requests': 'Aucune demande trouvée',
      'error_loading_requests': 'Erreur lors du chargement des demandes',
      // Admin Dashboard
      'admin_dashboard': 'Tableau de bord Admin',
      'admin_subtitle': 'Examiner et gérer les propriétés soumises',
      'pending': 'En attente',
      'published': 'Publiées',
      'rejected': 'Refusées',
      'property_approved': 'Propriété approuvée',
      'property_rejected': 'Propriété rejetée',
      'reject_property': 'Rejeter la propriété',
      'reject_reason': 'Motif du refus...',
      'view': 'Voir',
      'approve': 'Approuver',
      'no_properties_status': 'Aucune propriété %s',
      'untitled': 'Sans titre',
      'unknown_owner': 'Inconnu',
      'admin_dashboard_tab': 'Tableau de bord',
      'notifications': 'Notifications',
      'mark_all_read': 'Tout marquer comme lu',
      // Add Listing Screen
      'step_x_of_y': 'Étape %s sur %s',
      'fill_details_title': 'Remplissez les détails de votre',
      'real_estate': 'bien immobilier',
      'where_is_location': 'Où se trouve',
      'location_question': 'l\'emplacement',
      'add_photos_title': 'Ajoutez des',
      'photos_word': 'photos',
      'to_your_listing': 'à votre annonce',
      'almost_finish': 'Presque terminé',
      'complete_listing': ', complétez l\'annonce',
      'review_word': 'Vérifiez',
      'your_listing': 'votre annonce',
      'review_subtitle': 'Assurez-vous que tout est correct avant de publier.',
      'next': 'Suivant',
      'submit_for_review': 'Soumettre pour examen',
      'rent_price_month': 'Prix de location / Mois',
      'sell_price': 'Prix de vente',
      'title_label': 'Titre',
      'type_label': 'Type',
      'photos_label': 'Photos',
      'photo_count': 'photo(s)',
      'rooms_summary': 'chambre',
      'bath_summary': 'sdb',
      'balcony_summary': 'balcon',
      'kitchen_summary': 'cuisine',
      'facilities_label': 'Équipements',
      'submitted_for_review': 'Votre annonce a été\nsoumise pour examen',
      'submitted_review_desc': 'Notre équipe examinera votre propriété et la publiera sous peu. Vous pouvez suivre son statut dans Mes Annonces.',
      'parking_lot': 'Parking',
      'pet_allowed': 'Animaux acceptés',
      'garden': 'Jardin',
      'gym': 'Salle de sport',
      'park': 'Parc',
      'home_theatre': 'Home Cinéma',
      'kids_friendly': 'Adapté aux enfants',
      'wifi': 'WIFI',
      // Verify Email Screen
      'verify_email': 'Vérifier l\'e-mail',
      'check_your_email': 'Vérifiez votre e-mail',
      'verification_sent': 'Nous avons envoyé un code de vérification à 6 chiffres à',
      'verify': 'Vérifier',
      'didnt_receive': 'Vous n\'avez pas reçu le code ? ',
      'resend_in': 'Renvoyer dans',
      'resend': 'Renvoyer',
      'code_resent': 'Code de vérification renvoyé.',
      // Forgot Password Screen
      'forgot_password_title': 'Mot de passe oublié',
      'reset_password': 'Réinitialiser le mot de passe',
      'reset_password_desc': 'Entrez l\'adresse e-mail associée à votre compte et nous vous enverrons un code à 6 chiffres.',
      'send_code': 'Envoyer le code',
      'enter_code_title': 'Entrer le code',
      'code_sent_to': 'Nous avons envoyé un code à 6 chiffres à',
      'code_sent_suffix': '. Entrez-le ci-dessous avec votre nouveau mot de passe.',
      'digit_code': 'Code à 6 chiffres',
      'new_password': 'Nouveau mot de passe',
      'confirm_password': 'Confirmer le mot de passe',
      'valid_email_error': 'Veuillez entrer une adresse e-mail valide',
      'code_digits_error': 'Le code doit comporter 6 chiffres',
      'password_length_error': 'Le mot de passe doit comporter au moins 8 caractères',
      'passwords_match_error': 'Les mots de passe ne correspondent pas',
      'password_reset_success': 'Mot de passe réinitialisé avec succès ! Veuillez vous connecter.',
      // General & Call & Requests
      'failed_to_update_request_status': 'Échec de la mise à jour de l\'état de la demande',
      'no_requests': 'Aucune demande trouvée',
      'decline': 'Refuser',
      'accept': 'Accepter',
      'call_ended': 'Appel terminé',
      'location_not_set': 'Emplacement non défini',
      'tap_for_directions': 'Appuyez pour l\'itinéraire',
      'request_visit': 'Demander une visite',
      'request_type': 'Type de demande',
      'submit_request': 'Envoyer la demande',
      'owner_not_found': 'Propriétaire introuvable',
      'no_notifications_yet': 'Aucune notification pour le moment',
      'no_properties_found': 'Aucune propriété trouvée',
      'status_published': 'Publié',
      'status_available': 'Disponible',
      'status_hidden': 'Masqué',
      'status_rejected': 'Rejeté',
      'status_pending': 'En attente',
      'status_accepted': 'Accepté',
      'status_completed': 'Terminé',
      'request_type_visit': 'Visite',
      'request_updated_success': 'Demande mise à jour avec succès',
      'verification_failed': 'Échec de la vérification : ',
      'error_prefix': 'Erreur : ',
      'google_signin_failed': 'Échec de la connexion Google : ',
      'from': 'De : ',
      'to': 'À : ',
      'user': 'Utilisateur',
      'enable_location': 'Activer la localisation',
      'to_see_distance': 'pour voir la distance',
      'min_drive': 'min en voiture',
      'h_drive': 'h en voiture',
      'unknown_agent': 'Agent inconnu',
      'property_owner': 'Propriétaire',
      'unknown_location': 'Emplacement inconnu',
      'unknown_property': 'Propriété inconnue',
      'no_title': 'Sans titre',
      'logout_confirm': 'Êtes-vous sûr de vouloir vous déconnecter ?',
      'cancel': 'Annuler',
      'coming_soon_feature': 'Bientôt disponible',
      'request_sent_success': 'Demande envoyée avec succès.',
      'calling': 'Appel en cours...',
      'property': 'Propriété',
      'per_month': '/mois',
      'delete_property': 'Supprimer l\'annonce',
      'delete_property_confirm': 'Êtes-vous sûr de vouloir supprimer définitivement cette annonce ?',
      'delete': 'Supprimer',
      'enable': 'Activer',
      'disable': 'Désactiver',
      // Admin Categories
      'categories_tab': 'Catégories',
      'manage_categories': 'Gérer les catégories',
      'manage_categories_desc': 'Ajouter, modifier ou supprimer des catégories',
      'add_category': 'Ajouter une catégorie',
      'edit_category': 'Modifier la catégorie',
      'category_name_hint': 'ex. Appartement, Villa...',
      'category_created': 'Catégorie créée avec succès',
      'category_updated': 'Catégorie mise à jour avec succès',
      'category_deleted': 'Catégorie supprimée avec succès',
      'save_changes': 'Enregistrer',
      'create': 'Créer',
      'delete_category': 'Supprimer la catégorie',
      'confirm_delete_category': 'Voulez-vous vraiment supprimer "%s" ?',
      'category_has_properties': 'Impossible de supprimer "%n". Utilisée par %s propriétés.',
      'no_categories': 'Aucune catégorie trouvée',
      'add_first_category': 'Ajoutez votre première catégorie',
      'properties_count': 'propriétés',
      'category.apartment': 'Appartement',
      'category.villa': 'Villa',
      'category.studio': 'Studio',
      'category.house': 'Maison',
      'category.commercial': 'Commercial',
      'category.riad': 'Riad',
      'category.chalet': 'Chalet',
      'category.land': 'Terrain',
      'all': 'Tout',
      'agents': 'Agents',
      'categories': 'Catégories',
      'language_english': 'Anglais',
      'language_french': 'Français',
      'map_web_only': 'La vue carte n\'est prise en charge que sur le web pour le moment.',
      'unsupported_platform': 'Plateforme non supportée',
      'internal_key_optional': 'Clé interne (Optionnel)',
      'status_all': 'Tout',
      'status_available': 'Disponible',
      'status_sold': 'Vendu/Loué',
      'status_offplan': 'Sur plan',
      'delete_property': 'Supprimer la propriété',
      'delete_property_confirm': 'Êtes-vous sûr de vouloir supprimer définitivement cette propriété ?',
      'cancel': 'Annuler',
      'delete': 'Supprimer',
      'error_prefix': 'Erreur : ',
      'status_hidden': 'Masqué',
      'status_published': 'Publié',
      'status_pending': 'En attente',
      'status_rejected': 'Rejeté',
      'enable': 'Activer',
      'disable': 'Désactiver',
      'verification_failed': 'Échec de vérification : ',
      'fill_required_fields': 'Veuillez remplir tous les champs obligatoires',
      'error_loading_requests': 'Échec du chargement des demandes',
      'request_updated_success': 'Demande mise à jour avec succès',
      'failed_to_update_request_status': 'Échec de la mise à jour de la demande',
      'error': 'Erreur',
      'location': 'Emplacement',
      'calculating': 'Calcul en cours...',
      'status_accepted': 'Accepté',
      'status_completed': 'Terminé',
      'request_type_visit': 'Visite',
      'request_type_info': 'Information',
      'request_type_offer': 'Offre',
      'at_time': 'à',
      'reject': 'Refuser',
      'accept': 'Accepter',
      'ar_view': 'Vue AR',
      'status_updated': 'Statut mis à jour',
      'location_disabled': 'Les services de localisation sont désactivés.',
      'location_denied': 'Les autorisations de localisation sont refusées.',
      'location_denied_forever': 'Les autorisations de localisation sont définitivement refusées.',
      'map_clean': 'Plan',
      'map_satellite': 'Satellite',
      'all_morocco': 'Tout le Maroc',
      'search_location': 'Rechercher un lieu...',
    },
    'ar': {
      'welcome': 'مرحباً بكم في دارنا',
      'welcome_subtitle':
          'اكتشف العقار المثالي في المغرب.\nرحلتك إلى بيت جديد تبدأ من هنا.',
      'get_started': 'ابدأ الآن',
      'signin': 'تسجيل الدخول',
      'signup': 'إنشاء حساب',
      'email': 'البريد الإلكتروني',
      'password': 'كلمة المرور',
      'forgot_password': 'هل نسيت كلمة المرور؟',
      'or': 'أو',
      'dont_have_account': 'ليس لديك حساب؟ ',
      'already_have_account': 'لديك حساب بالفعل؟ ',
      'full_name': 'الاسم الكامل',
      'phone': 'رقم الهاتف',
      'create_account': 'أنشئ حسابك للمتابعة',
      'account_created': 'تم إنشاء الحساب!',
      'welcome_darna': 'مرحباً بك في عائلة دارنا!',
      'profile': 'الملف الشخصي',
      'edit_profile': 'تعديل الملف الشخصي',
      'settings': 'الإعدادات',
      'language': 'اللغة',
      'dark_mode': 'الوضع الليلي',
      'light_mode': 'الوضع النهاري',
      'logout': 'تسجيل الخروج',
      'coming_soon': 'قريباً!',
      'update': 'تحديث الملف',
      'success': 'نجاح',
      'profile_updated': 'تم تحديث الملف الشخصي بنجاح!',
      'social_accounts': 'الحسابات الاجتماعية',
      'link': 'ربط',
      'unlink': 'إلغاء الربط',
      'listings_count': 'العقارات',
      'sold_count': 'المباعة',
      'reviews_count': 'التقييمات',
      'transactions_count': 'المعاملات',
      'no_sold_properties': 'لا توجد عقارات مباعة',
      'no_sold_subtitle': 'عقاراتك المباعة ستظهر هنا',
      'hello': 'مرحباً 👋',
      'categories': 'الفئات',
      'featured_properties': 'عقارات مميزة',
      'best_deals': 'أفضل العروض لك',
      'top_locations': 'أفضل المواقع',
      'explore_popular': 'استكشف المناطق الشهيرة',
      'best_for_rent': 'الأفضل للإيجار',
      'monthly_rental': 'خيارات الإيجار الشهري',
      'best_for_sale': 'الأفضل للشراء',
      'properties_for_sale': 'عقارات متاحة للشراء',
      'no_sale_found': 'لا توجد عقارات متاحة للشراء',
      'search_properties': 'البحث عن عقارات...',
      'see_all': 'عرض الكل',
      'explore': 'استكشاف',
      'properties': 'عقارات',
      'agents': 'وكلاء',
      'listings_suffix': 'عقار',
      'no_notifications': 'لا توجد إشعارات',
      'no_notifications_desc': 'عندما تتلقى إشعارات، ستظهر هنا',
      // Navigation
      'nav_home': 'الرئيسية',
      'nav_search': 'بحث',
      'nav_favorites': 'المفضلة',
      'nav_profile': 'حسابي',
      'nav_messages': 'الرسائل',
      // Chat
      'messages': 'الرسائل',
      'conversations': 'المحادثات',
      'no_conversations': 'لا توجد محادثات',
      'no_conversations_desc':
          'ابدأ المحادثة عبر التواصل مع مالك العقار من صفحة التفاصيل.',
      'no_messages': 'لا توجد رسائل. قل مرحبا!',
      'type_message': 'اكتب رسالة...',
      'send': 'إرسال',
      'chat_auto_message': 'سلام، أنا مهتم بهذا العقار.',
      'cannot_chat_own': 'لا يمكنك الدردشة حول عقارك الخاص.',
      'typing': 'يكتب...',
      'online': 'متصل',
      'last_seen': 'آخر ظهور',
      'delete_for_me': 'حذف عندي',
      'delete_for_everyone': 'حذف عند الجميع',
      'message_deleted': 'تم حذف هذه الرسالة',
      'recording': 'جاري التسجيل...',

      // Reviews & Ratings
      'leave_review': 'أضف تقييم',
      'edit_review': 'تعديل التقييم',
      'delete_review': 'حذف التقييم',
      'submit_review': 'إرسال التقييم',
      'review_success': 'تم إرسال التقييم بنجاح',
      'review_updated_success': 'تم تحديث التقييم بنجاح',
      'review_deleted_success': 'تم حذف التقييم بنجاح',
      'owner_review_error': 'لا يمكنك تقييم عقارك الخاص.',
      'duplicate_review_error': 'لقد قمت بتقييم هذا العقار مسبقاً.',
      'rating_required': 'يرجى تحديد تقييم من (1-5) نجوم.',

      // Property Details
      'bedrooms': 'غرف نوم',
      'bathroom': 'حمام',
      'location_facilities': 'الموقع والمرافق العامة',
      'cost_of_living': 'تكلفة المعيشة',
      'see_details': 'عرض التفاصيل',
      'reviews': 'التقييمات',
      'view_all_reviews': 'عرض كل التقييمات',
      'view_property': 'عرض العقار',
      'view_on_map': 'عرض على الخريطة',
      'nearby_properties': 'عقارات قريبة',
      'nearby_location': 'بالقرب من هذا الموقع',
      'mad': 'درهم',
      'month': 'شهر',
      'drive': 'قيادة',
      'map_view': 'خريطة',
      'contact_agent': 'اتصل بالوكيل (قريباً)',
      'ar_view': 'الواقع المعزز (قريباً)',
      'my_favorites': 'مفضلاتي',
      'favorites': 'المفضلة',
      'favorite': 'المفضلة',
      'clear_all': 'مسح الكل',
      'empty_favorites_title': 'صفحة المفضلة لديك فارغة',
      'empty_favorites_subtitle':
          'انقر فوق زر الإضافة أعلاه لبدء الاستكشاف واختيار عقاراتك المفضلة.',
      'explore_estates': 'استكشاف العقارات',
      'browse_as_guest': 'تصفح كزائر',
      'recent_properties': 'عقارات حديثة',
      'recently_added': 'أحدث الإعلانات المضافة',
      'customers': 'العملاء',
      // Categories
      'all': 'الكل',
      'house': 'منزل',
      'apartment': 'شقة',
      'villa': 'فيلا',
      'commercial': 'محل تجاري',
      'land': 'أرض',
      'riad': 'رياض',
      'studio': 'ستوديو',
      'chalet': 'شاليه',
      // Alerts & Actions
      'require_login': 'المرجو تسجيل الدخول أولاً',
      'cannot_buy_own': 'لا يمكنك شراء عقارك الخاص.',
      'cannot_rent_own': 'لا يمكنك استئجار عقارك الخاص.',
      'ok': 'حسنا',
      'cancel': 'إلغاء',
      'confirm': 'تأكيد',
      'rent_property': 'استئجار العقار',
      'start_date': 'تاريخ البدء',
      'months': 'الأشهر: ',
      'no_listings_found': 'لم يتم العثور على أي عقار',
      'no_featured_found': 'لم يتم العثور على عقارات مميزة.',
      'no_rental_found': 'لم يتم العثور على عقارات للإيجار.',
      'no_properties_found': 'لم يتم العثور على عقارات.',
      'error': 'خطأ: ',
      'fill_required_fields': 'المرجو ملء جميع الحقول الإلزامية',
      'change_location': 'تغيير الموقع',
      'failed_avatar': 'فشل تحميل الصورة الشخصية: ',
      // Transactions
      'buy': 'شراء',
      'rent_now': 'استئجار',
      'price': 'السعر',
      'status_completed': 'مكتمل',
      'status_canceled': 'ملغى',
      'status_pending': 'قيد الانتظار',
      'status_active': 'نشط',
      'update_profile_failed':
          'فشل تحديث الملف الشخصي. يرجى المحاولة مرة أخرى.',
      'phone_number': 'رقم الهاتف',
      'cost_desc_not_avail': 'وصف التكلفة غير متوفر.',
      'trans_price': 'السعر:',
      'trans_seller': 'البائع',
      'trans_buyer': 'المشتري',
      'trans_owner': 'المالك',
      'trans_tenant': 'المكتري',
      'down_payment_help': 'دفعة أولى/الدفع الكامل',
      'monthly_budget_help': 'ميزانيتك الشهرية',
      'rooms': 'غرف',
      // Filters & Forms
      'payment_cash': 'دفع نقداً',
      'payment_monthly': 'دفعات شهرية',
      'number_of_rooms': 'عدد الغرف',
      'property_type': 'نوع العقار',
      'property_status': 'حالة العقار',
      'find_my_home': 'ابحث عن بيتي',
      'enter_location': 'أدخل الموقع',
      'house_for_sale': 'منزل للبيع',
      'phone_number_hint': 'رقم الهاتف',
      'map_placeholder': 'مكان الخريطة',
      'add_listing': 'أضف إعلان',
      'update_listing': 'تحديث الإعلان',
      'listing_type': 'نوع الإعلان',
      'rent_price_label': 'سعر الإيجار (درهم/شهر)',
      'sell_price_label': 'سعر البيع (درهم)',
      'area_label': 'المساحة (م²)',
      'features': 'مميزات العقار',
      'location': 'الموقع',
      'listing_photos': 'صور الإعلان',
      'edit_location': 'تعديل الموقع',
      'contact_info': 'معلومات التواصل',
      'discover': 'اكتشف',
      'find_perfect': 'ابحث عن عقارك المثالي',
      'sort': 'ترتيب',
      'sort_by': 'ترتيب حسب',
      'sort_default': 'الافتراضي',
      'sort_price_asc': 'السعر: من الأقل للأعلى',
      'sort_price_desc': 'السعر: من الأعلى للأقل',
      'sort_rating': 'التقييم',
      'property_singular': 'عقار',
      'property_plural': 'عقارات',
      'no_properties_desc': 'لم نجد أي عقار يطابق بحثك.',
      'reset_filters': 'إعادة تعيين',
      'listing_now_published_1': 'إعلانك الآن\n',
      'listing_now_published_2': 'منشور',
      'listing_success_desc': 'تهانينا على نشر الإعلان بنجاح.',
      'add_more': 'أضف المزيد',
      'finish': 'إنهاء',
      'listing_title': 'عنوان الإعلان',
      'enter_title': 'أدخل عنوان الإعلان',
      'property_category': 'فئة العقار',
      'for_rent': 'إيجار',
      'for_sale': 'بيع',
      'bedroom': 'غرفة النوم',
      'balcony': 'شرفة',
      'kitchen': 'مطبخ',
      'toilet': 'دورة المياه',
      'living_room': 'غرفة المعيشة',
      'total_rooms': 'مجموع الغرف',
      'environment_facilities': 'البيئة / المرافق',
      'edit_phone': 'تعديل رقم الهاتف',
      'close': 'إغلاق',
      'listing_updated_1': 'تم تحديث\n',
      'listing_updated_2': 'إعلانك بنجاح',
      'trans_from': 'من:',
      'trans_to': 'إلى:',
      'trans_reject': 'رفض',
      'trans_accept': 'قبول',
      'trans_terminate': 'إنهاء',
      'trans_no_found': 'لا توجد معاملات.',
      'my_transactions': 'معاملاتي',
      'mes_achats': 'مشترياتي',
      'mes_ventes': 'مبيعاتي',
      'mes_locations': 'إيجاراتي',
      'biens_loues': 'عقاراتي المؤجرة',
      'join_darna_today': 'انضم إلى دارنا اليوم!',
      'guest_signup_prompt':
          'سجل الدخول أو أنشئ حساباً لحفظ مفضلاتك،\nوالتواصل مع الوكلاء والمزيد.',
      'browsing_as_guest': 'تصفح كزائر',
      'signin_full_access': 'سجل الدخول للوصول الكامل',
      'unlock_full_access': 'استفد من الوصول الكامل',
      'unlock_subtitle':
          'احفظ مفضلاتك، تواصل مع الوكلاء\nوتصفح جميع الإعلانات.',
      'signin_now': 'سجل الدخول الآن ←',
      // Property Request
      'request_visit': 'طلب زيارة',
      'request_type': 'نوع الطلب',
      'preferred_date': 'التاريخ المفضل',
      'preferred_time': 'الوقت المفضل',
      'message_optional': 'رسالة (اختياري)',
      'submit_request': 'إرسال الطلب',
      'visit': 'جدولة زيارة',
      'rent_interest': 'مهتم بالإيجار',
      'buy_interest': 'مهتم بالشراء',
      'cannot_request_own': 'لا يمكنك طلب عقارك الخاص.',
      'comment': 'اكتب تعليقك...',
      'my_requests': 'طلباتي',
      'sent_requests': 'المرسلة',
      'received_requests': 'المستلمة',
      'accept': 'قبول',
      'reject': 'رفض',
      'no_requests': 'لا توجد طلبات',
      'error_loading_requests': 'فشل تحميل الطلبات',
      // Admin Dashboard
      'admin_dashboard': 'لوحة تحكم المشرف',
      'admin_subtitle': 'مراجعة وإدارة العقارات المقدمة',
      'pending': 'قيد الانتظار',
      'published': 'منشورة',
      'rejected': 'مرفوضة',
      'property_approved': 'تمت الموافقة على العقار',
      'property_rejected': 'تم رفض العقار',
      'reject_property': 'رفض العقار',
      'reject_reason': 'سبب الرفض...',
      'view': 'عرض',
      'approve': 'موافقة',
      'no_properties_status': 'لا توجد عقارات %s',
      'untitled': 'بدون عنوان',
      'unknown_owner': 'غير معروف',
      'admin_dashboard_tab': 'لوحة التحكم',
      'notifications': 'الإشعارات',
      'mark_all_read': 'تعليم الكل كمقروء',
      // Add Listing Screen
      'step_x_of_y': 'الخطوة %s من %s',
      'fill_details_title': 'أدخل تفاصيل',
      'real_estate': 'عقارك',
      'where_is_location': 'أين يقع',
      'location_question': 'الموقع',
      'add_photos_title': 'أضف',
      'photos_word': 'صور',
      'to_your_listing': 'إلى إعلانك',
      'almost_finish': 'أوشكت على الانتهاء',
      'complete_listing': '، أكمل الإعلان',
      'review_word': 'راجع',
      'your_listing': 'إعلانك',
      'review_subtitle': 'تأكد من أن كل شيء يبدو جيداً قبل النشر.',
      'next': 'التالي',
      'submit_for_review': 'إرسال للمراجعة',
      'rent_price_month': 'سعر الإيجار / الشهر',
      'sell_price': 'سعر البيع',
      'title_label': 'العنوان',
      'type_label': 'النوع',
      'photos_label': 'الصور',
      'photo_count': 'صورة',
      'rooms_summary': 'غرفة',
      'bath_summary': 'حمام',
      'balcony_summary': 'شرفة',
      'kitchen_summary': 'مطبخ',
      'facilities_label': 'المرافق',
      'submitted_for_review': 'تم إرسال إعلانك\nللمراجعة',
      'submitted_review_desc': 'سيراجع فريقنا عقارك وينشره قريباً. يمكنك متابعة حالته في إعلاناتي.',
      'parking_lot': 'موقف سيارات',
      'pet_allowed': 'الحيوانات مسموحة',
      'garden': 'حديقة',
      'gym': 'صالة رياضية',
      'park': 'منتزه',
      'home_theatre': 'سينما منزلية',
      'kids_friendly': 'مناسب للأطفال',
      'wifi': 'واي فاي',
      // Verify Email Screen
      'verify_email': 'التحقق من البريد الإلكتروني',
      'check_your_email': 'تحقق من بريدك الإلكتروني',
      'verification_sent': 'لقد أرسلنا رمز تحقق مكون من 6 أرقام إلى',
      'verify': 'تحقق',
      'didnt_receive': 'لم تستلم الرمز؟ ',
      'resend_in': 'إعادة الإرسال خلال',
      'resend': 'إعادة الإرسال',
      'code_resent': 'تم إعادة إرسال رمز التحقق.',
      // Forgot Password Screen
      'forgot_password_title': 'نسيت كلمة المرور',
      'reset_password': 'إعادة تعيين كلمة المرور',
      'reset_password_desc': 'أدخل عنوان البريد الإلكتروني المرتبط بحسابك وسنرسل لك رمزاً مكوناً من 6 أرقام.',
      'send_code': 'إرسال الرمز',
      'enter_code_title': 'أدخل الرمز',
      'code_sent_to': 'أرسلنا رمزاً مكوناً من 6 أرقام إلى',
      'code_sent_suffix': '. أدخله أدناه مع كلمة مرورك الجديدة.',
      'digit_code': 'الرمز المكون من 6 أرقام',
      'new_password': 'كلمة المرور الجديدة',
      'confirm_password': 'تأكيد كلمة المرور',
      'valid_email_error': 'يرجى إدخال عنوان بريد إلكتروني صالح',
      'code_digits_error': 'يجب أن يتكون الرمز من 6 أرقام',
      'password_length_error': 'يجب أن تتكون كلمة المرور من 8 أحرف على الأقل',
      'passwords_match_error': 'كلمتا المرور غير متطابقتين',
      'password_reset_success': 'تم إعادة تعيين كلمة المرور بنجاح! يرجى تسجيل الدخول.',
      // General & Call & Requests
      'failed_to_update_request_status': 'فشل تحديث حالة الطلب',
      'no_requests': 'لم يتم العثور على طلبات',
      'decline': 'رفض',
      'accept': 'قبول',
      'call_ended': 'انتهت المكالمة',
      'location_not_set': 'الموقع غير محدد',
      'tap_for_directions': 'انقر للحصول على الاتجاهات',
      'request_visit': 'طلب زيارة',
      'request_type': 'نوع الطلب',
      'submit_request': 'إرسال الطلب',
      'owner_not_found': 'المالك غير موجود',
      'no_notifications_yet': 'لا توجد إشعارات بعد',
      'no_properties_found': 'لم يتم العثور على عقارات',
      'status_published': 'منشور',
      'status_available': 'متاح',
      'status_hidden': 'مخفي',
      'status_rejected': 'مرفوض',
      'status_pending': 'قيد الانتظار',
      'status_accepted': 'مقبول',
      'status_completed': 'مكتمل',
      'request_type_visit': 'زيارة',
      'request_updated_success': 'تم تحديث الطلب بنجاح',
      'verification_failed': 'فشل التحقق: ',
      'error_prefix': 'خطأ: ',
      'google_signin_failed': 'فشل تسجيل الدخول عبر Google: ',
      'from': 'من: ',
      'to': 'إلى: ',
      'user': 'مستخدم',
      'enable_location': 'تفعيل الموقع',
      'to_see_distance': 'لرؤية المسافة',
      'min_drive': 'دقيقة بالسيارة',
      'h_drive': 'ساعة بالسيارة',
      'unknown_agent': 'وكيل غير معروف',
      'property_owner': 'مالك العقار',
      'unknown_location': 'موقع غير معروف',
      'unknown_property': 'عقار غير معروف',
      'no_title': 'بدون عنوان',
      'logout_confirm': 'هل أنت متأكد أنك تريد تسجيل الخروج؟',
      'cancel': 'إلغاء',
      'coming_soon_feature': 'قريباً',
      'request_sent_success': 'تم إرسال الطلب بنجاح.',
      'calling': 'جاري الاتصال...',
      'property': 'عقار',
      'per_month': '/شهر',
      'delete_property': 'حذف الإعلان',
      'delete_property_confirm': 'هل أنت متأكد أنك تريد حذف هذا الإعلان نهائياً؟',
      'delete': 'حذف',
      'enable': 'تفعيل',
      'disable': 'تعطيل',
      // Admin Categories
      'categories_tab': 'الفئات',
      'manage_categories': 'إدارة الفئات',
      'manage_categories_desc': 'إضافة، تعديل أو حذف فئات العقارات',
      'add_category': 'إضافة فئة',
      'edit_category': 'تعديل الفئة',
      'category_name_hint': 'مثال: شقة، فيلا...',
      'category_created': 'تم إنشاء الفئة بنجاح',
      'category_updated': 'تم تحديث الفئة بنجاح',
      'category_deleted': 'تم حذف الفئة بنجاح',
      'save_changes': 'حفظ التغييرات',
      'create': 'إنشاء',
      'delete_category': 'حذف الفئة',
      'confirm_delete_category': 'هل أنت متأكد أنك تريد حذف "%s"؟',
      'category_has_properties': 'لا يمكن حذف "%n". مستخدمة بواسطة %s عقارات.',
      'no_categories': 'لم يتم العثور على فئات',
      'add_first_category': 'أضف فئتك الأولى',
      'properties_count': 'عقارات',
      'category.apartment': 'شقة',
      'category.villa': 'فيلا',
      'category.studio': 'استوديو',
      'category.house': 'منزل',
      'category.commercial': 'تجاري',
      'category.riad': 'رياض',
      'category.chalet': 'شاليه',
      'category.land': 'أرض',
      'all': 'الكل',
      'agents': 'الوكلاء',
      'categories': 'الفئات',
      'language_english': 'الإنجليزية',
      'language_french': 'الفرنسية',
      'map_web_only': 'عرض الخريطة مدعوم فقط على الويب حالياً.',
      'unsupported_platform': 'منصة غير مدعومة',
      'internal_key_optional': 'مفتاح داخلي (اختياري)',
      'status_all': 'الكل',
      'status_available': 'متاح',
      'status_sold': 'مباع/مؤجر',
      'status_offplan': 'على المخطط',
      'delete_property': 'حذف العقار',
      'delete_property_confirm': 'هل أنت متأكد أنك تريد حذف هذا العقار نهائياً؟',
      'cancel': 'إلغاء',
      'delete': 'حذف',
      'error_prefix': 'خطأ: ',
      'status_hidden': 'مخفي',
      'status_published': 'منشور',
      'status_pending': 'قيد الانتظار',
      'status_rejected': 'مرفوض',
      'enable': 'تفعيل',
      'disable': 'تعطيل',
      'verification_failed': 'فشل التحقق: ',
      'fill_required_fields': 'يرجى ملء جميع الحقول المطلوبة',
      'error_loading_requests': 'فشل في تحميل الطلبات',
      'request_updated_success': 'تم تحديث الطلب بنجاح',
      'failed_to_update_request_status': 'فشل في تحديث حالة الطلب',
      'error': 'خطأ',
      'location': 'الموقع',
      'calculating': 'جاري الحساب...',
      'status_accepted': 'مقبول',
      'status_completed': 'مكتمل',
      'request_type_visit': 'زيارة',
      'request_type_info': 'معلومات',
      'request_type_offer': 'عرض',
      'at_time': 'في',
      'reject': 'رفض',
      'accept': 'قبول',
      'ar_view': 'عرض AR',
      'status_updated': 'تم تحديث الحالة',
      'location_disabled': 'خدمات الموقع معطلة.',
      'location_denied': 'أذونات الموقع مرفوضة.',
      'location_denied_forever': 'أذونات الموقع مرفوضة بشكل دائم.',
      'map_clean': 'خريطة',
      'map_satellite': 'قمر صناعي',
      'all_morocco': 'كل المغرب',
      'search_location': 'ابحث عن موقع...',
    },
  };

  void setLanguage(String languageCode) async {
    _locale = Locale(languageCode);
    notifyListeners();
    AppRouter.router.refresh();
    final prefs = await SharedPreferences.getInstance();
    await prefs.setString('language_code', languageCode);
  }

  void _loadLanguage() async {
    final prefs = await SharedPreferences.getInstance();
    final languageCode = prefs.getString('language_code') ?? 'en';
    _locale = Locale(languageCode);
    _isLoading = false;
    notifyListeners();
  }

  String translate(String key) {
    return _translations[_locale.languageCode]?[key] ?? key;
  }
}

extension LocalizationExtension on BuildContext {
  String tr(String key) =>
      Provider.of<LanguageProvider>(this, listen: false).translate(key);
}
